// Every kind of board line the server writes (activity.kind: post_activity and the *_tell helpers in the migrations,
// the dailies' signing, the member and bidder invite functions, the worker's file scan). The board's type filter lists
// all of them, not only the kinds on the pages loaded so far. A kind the server adds later still shows once a line of
// it has loaded. Data about the code, not about any job.
const SERVER_KINDS = [
  'addendum.issued',
  'bid.answer',
  'bid.intent',
  'bid.invited',
  'bid.question',
  'bid.received',
  'comment.added',
  'comment.edited',
  'correction.corrected',
  'correction.opened',
  'correction.ready',
  'correction.reopened',
  'correction.signed_off',
  'daily.resubmitted',
  'daily.submitted',
  'delivery.posted',
  'file_infected',
  'ir.gc_review',
  'ir.helper',
  'ir.helper_report',
  'ir.moved',
  'ir.ofs',
  'ir.postponed',
  'ir.requested',
  'ir.results',
  'ir.returned',
  'ir.withdrawn',
  'member.invited',
  'member.joined',
  'member.revoked',
  'permit.approved_set',
  'permit.comment',
  'permit.created',
  'permit.response',
  'permit.review',
  'permit.stage',
  'requirements.due',
  'requirements.evidence',
  'rfi.answered',
  'rfi.asked',
  'rfi.closed',
  'rfi.impact_claimed',
  'rfi.impact_note',
  'rfi.issued',
  'rfi.returned',
  'rfi.review',
  'rfi.to_issue',
  'rfi.voided',
  'safety.closed',
  'safety.tailgate_due',
  'schedule.published',
  'schedule.update_due',
] as const;

/** The filter's kinds: every server kind plus any other kind already loaded, each once, in order. */
export function filterKinds(loaded: readonly string[]): string[] {
  return [...new Set<string>([...SERVER_KINDS, ...loaded])].sort();
}
